[package]
name = "anchor-wl-clipboard"
version = "0.1.0"
edition = "2024"
description = "Wayland clipboard access with X11/XWayland fallback"
license = "MIT"
repository = "https://github.com/anchor-software-org/anchor-wl-clipboard"
readme = "README.md"

[dependencies]
wayland-client = "0.31"
wayland-protocols-wlr = { version = "0.3", features = ["client"] }
os_pipe = "1"
log = "0.4"
x11-clipboard = "0.9.3"
wayland-clipboard-backend = { package = "wl-clipboard-rs", version = "0.9.3" }
